import '../globals.css'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { dark } from '@clerk/themes'
import {Toaster} from 'react-hot-toast'
const inter = Inter({ subsets: ['latin'] })
import Providers from '@/redux/provider/Providers'
export const metadata = {
  title: 'Threads',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
     <ClerkProvider
    appearance={{
      baseTheme: dark,
    }}
    >
      <html lang="en">
        <body className={`${inter.className} bg-dark-1 w-full min-h-[100vh] flex justify-center items-center `}>
          {children}
          <Toaster/>
        </body>
      </html>
    </ClerkProvider>
  )
}
